### ISSUE TITLE
Parallels Desktop 14.1.3 有么？

### ISSUE THREAD

**Issue by elefaint** [devzwy/Crack-Edition-software-for-Mac#10]

**Comment by devzwy** [comment]
抽时间给你更新下。

**Comment by fhefh2015** [comment]
https://www.macbed.cn/mac/4
只找到了14.1.2

**Comment by devzwy** [comment]
对的，只有14.1.2 @ @elefaint  @fhefh2015

**Comment by devzwy** [comment]
@elefaint @fhefh2015 [see this](https://github.com/devzwy/Crack-Edition-software-for-Mac/blob/master/README_ZH.MD#12)
