### ISSUE TITLE
Clean My Mac download link not working.

### ISSUE THREAD

**Issue by yangbaiboot** [devzwy/Crack-Edition-software-for-Mac#18]

**Comment by devzwy** [comment]
Please leave your Email and I will send it to you privately. @yangbaiboot

**Comment by yangbaiboot** [comment]
@devzwy neobai@qq.com Thanks.

**Comment by devzwy** [comment]
> @devzwy [neobai@qq.com](mailto:neobai@qq.com) Thanks.

Has been sent, please check.

**Comment by who0sy** [comment]
兄弟给我也发一下吧啊 whoosys@gmail.com @devzwy

**Comment by who0sy** [comment]
Also send me, brother. @devzwy  email:whoosys@gmail.com

**Comment by devzwy** [comment]
> Also send me, brother. @devzwy email:[whoosys@gmail.com](mailto:whoosys@gmail.com)

发了，注意查收。

**Comment by YuuhangXie** [comment]
xie0806@126.com  谢谢！

**Comment by YuuhangXie** [comment]
@devzwy xie0806@126.com 谢谢！

**Comment by who0sy** [comment]
> > Also send me, brother. @devzwy email:[whoosys@gmail.com](mailto:whoosys@gmail.com)
> 
> 发了，注意查收。

没收到。，。。再发一次兄弟

**Comment by devzwy** [comment]
@YuuhangXie @who0sy 已发送

**Comment by doubleJJJJ** [comment]
517469920@qq.com,谢谢了

**Comment by doubleJJJJ** [comment]
@devzwy 517469920@qq.com，麻烦发一下，谢谢了

**Comment by Bbcomb** [comment]
兄弟也发我下ddcomb666@gmail.com
