### ISSUE TITLE
 ClearMyMac 不能用 10.14.2 (18C54)

### ISSUE THREAD

**Issue by JessonYue** [devzwy/Crack-Edition-software-for-Mac#5]

**Comment by devzwy** [comment]
按照我的教程一步一步来，我就是10.14.2的系统。哪里有问题贴图出来。 @JessonYue

**Comment by JessonYue** [comment]
多谢回复，教程上说直接安装 就自动破解了 我安装了但是点击的时候出现下面的错误。
![image](https://user-images.githubusercontent.com/25720897/51374995-9ea4c980-1b3f-11e9-9980-258a26588526.png)

**Comment by JessonYue** [comment]
sorry fix了 。是我没打开安全策略
