### ISSUE TITLE
好像迅雷和Cleanmymac都失效了

### ISSUE THREAD

**Issue by tycallen** [devzwy/Crack-Edition-software-for-Mac#7]
如题

**Comment by devzwy** [comment]
我抽时间更新一下，谢谢反馈。

**Comment by devzwy** [comment]
@tycallen 已经更新下载地址，请点击 [ClearMyMac](https://github.com/devzwy/Crack-Edition-software-for-Mac/blob/master/README_ZH.MD#1)再次尝试。

**Comment by tycallen** [comment]
thanks!
