### ISSUE TITLE
求paw的破解版

### ISSUE THREAD

**Issue by hpustudent** [devzwy/Crack-Edition-software-for-Mac#9]
rt

**Comment by devzwy** [comment]
这段时间忙完我看一下。

**Comment by devzwy** [comment]
@hpustudent See [PawForMac](https://github.com/devzwy/Crack-Edition-software-for-Mac/blob/master/README_ZH.MD#目录)

**Comment by hpustudent** [comment]
> @hpustudent See [PawForMac](https://github.com/devzwy/Crack-Edition-software-for-Mac/blob/master/README_ZH.MD#%E7%9B%AE%E5%BD%95)
谢谢可以用了
